version : '3'

services:
    lb:
        image: haproxy:1.6
        volumes:
            - ./haproxy:/haproxy-override
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            - "8080:8080"
    nodeapp1:
        restart: always
        build: .
        volumes:
            - ./:/code
        environment:
            - APPID=1111
    nodeapp2:
        restart: always
        build: .
        volumes:
            - ./:/code
        environment:
            - APPID=2222
    nodeapp3:
        restart: always
        build: .
        volumes:
            - ./:/code
        environment:
            - APPID=3333
    nodeapp4:
        restart: always
        build: .
        volumes:
            - ./:/code
        environment:
            - APPID=4444
        